services:
  - type: cron
    name: nas100-bias-job
    runtime: python
    schedule: "*/15 * * * *"  # ogni 15 minuti
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
